// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using newprojectsas.Data;

#nullable disable

namespace newprojectsas.Migrations
{
    [DbContext(typeof(newprojectsasContext))]
    [Migration("20230917054454_INIT")]
    partial class INIT
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("newprojectsas.Controllers.Models.admissioninfo", b =>
                {
                    b.Property<int>("addid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("addid"), 1L, 1);

                    b.Property<int>("courseid")
                        .HasColumnType("int");

                    b.Property<int>("studid")
                        .HasColumnType("int");

                    b.HasKey("addid");

                    b.HasIndex("courseid");

                    b.HasIndex("studid");

                    b.ToTable("admissioninfo");
                });

            modelBuilder.Entity("newprojectsas.Controllers.Models.course", b =>
                {
                    b.Property<int>("courseid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("courseid"), 1L, 1);

                    b.Property<string>("coursedescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("coursefees")
                        .HasColumnType("int");

                    b.Property<string>("courselink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("coursename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("courseid");

                    b.ToTable("course");
                });

            modelBuilder.Entity("newprojectsas.Controllers.Models.stdinfo", b =>
                {
                    b.Property<int>("stdid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("stdid"), 1L, 1);

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("confirm_password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("phoneno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stdname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usertype")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("stdid");

                    b.ToTable("stdinfo");
                });

            modelBuilder.Entity("newprojectsas.Controllers.Models.admissioninfo", b =>
                {
                    b.HasOne("newprojectsas.Controllers.Models.course", "course")
                        .WithMany()
                        .HasForeignKey("courseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("newprojectsas.Controllers.Models.stdinfo", "stdinfo")
                        .WithMany()
                        .HasForeignKey("studid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("stdinfo");
                });
#pragma warning restore 612, 618
        }
    }
}
